### ISSUE TITLE
Login - manual login

### ISSUE THREAD

**Issue by uumoss-bb** [uumoss-bb/NOX-2.0#50]

**Comment by stozea** [comment]
I'm not sure how big of a task this is, I just think its important for a few reasons:

1. We can store more users
2. All though a big part of the population has FB not everyone does. I'd love to capture all traffic.

**Comment by uumoss-bb** [comment]
1. It wont have anything to anything with the amout of users we can have
2. I can see people (like my dad) who wont want to sign in with FB.

3. I say this is something we save for last, This is a bigger change.
